const formadores = [
  {
    id: "0",
    name: "António",
    surname: "Macamo",
    area: ["math"],
    active: true,
  },
  {
    id: "1",
    name: "Jorge Alexandre",
    surname: "Timane",
    area: ["pt"],
    active: true,
  },
  {
    id: "2",
    name: "Cláudio Artur",
    surname: "Maxlhaieie",
    area: ["math"],
    active: true,
  },
  {
    id: "3",
    name: "Sairesse",
    surname: "Victorino",
    area: ["math"],
    active: true,
  },
  {
    id: "4",
    name: "Edmilson Armando",
    surname: "Cande",
    area: ["psi"],
    active: true,
  },
  {
    id: "5",
    name: "Armando Curas",
    surname: "Cande",
    area: ["eng"],
    active: true,
  },
  {
    id: "6",
    name: "Serafim",
    surname: "Geraldo",
    area: ["eng"],
    active: true,
  },
  {
    id: "7",
    name: "Feliciano",
    surname: "Matsimbe",
    area: ["eng"],
    active: true,
  },
  {
    id: "8",
    name: "Armando Zacarias",
    surname: "Mambasse",
    area: ["math"],
    active: true,
  },
  {
    id: "9",
    name: "Maria Elisa",
    surname: "Macuácua",
    area: ["psi"],
    active: true,
  },
  {
    id: "10",
    name: "Lurdes",
    surname: "Dolane",
    area: ["psi"],
    active: true,
  },
  {
    id: "11",
    name: "Açucena",
    surname: "",
    area: ["psi"],
    active: true,
  },
  {
    id: "12",
    name: "Mário",
    surname: "Alberto",
    area: ["psi"],
    active: true,
  },
  {
    id: "13",
    name: "Miguel",
    surname: "Alberto",
    area: ["psi"],
    active: true,
  },
  {
    id: "14",
    name: "Alexandre",
    surname: "",
    area: ["asri"],
    active: true,
  },
  {
    id: "15",
    name: "Pedro",
    surname: "",
    area: ["asri"],
    active: true,
  },
];
